---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logstash
  namespace: monitoring
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
    path: apps/logstash
    repoURL: 'https://github.com/gitafolabi/argo-helm-k8s-complete'
    targetRevision: HEAD
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
